package com.duanxin.distributelock.mapper;

import com.duanxin.distributelock.entity.DistributeLock;
import java.util.List;

public interface DistributeLockMapper {

    /**
     * 获取分布式锁
     * @param businessCode
     * @date 2020/5/31 14:03
     * @return com.duanxin.distributelock.entity.DistributeLock
     */
    DistributeLock selectDistributeLock(String businessCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_lock
     *
     * @mbg.generated Sun May 31 11:00:10 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_lock
     *
     * @mbg.generated Sun May 31 11:00:10 CST 2020
     */
    int insert(DistributeLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_lock
     *
     * @mbg.generated Sun May 31 11:00:10 CST 2020
     */
    DistributeLock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_lock
     *
     * @mbg.generated Sun May 31 11:00:10 CST 2020
     */
    List<DistributeLock> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distribute_lock
     *
     * @mbg.generated Sun May 31 11:00:10 CST 2020
     */
    int updateByPrimaryKey(DistributeLock record);
}