server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/distribute?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
  ## redis
  redis:
    database: 0
    host: 192.168.100.137
    port: 6379
    password: root

mybatis:
  type-aliases-package: com.duanxin.distributelock.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml
